### ISSUE TITLE
Check / update notebook examples with Cartopy.

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [pyugrid/pyugrid#108]
We should make sure these still work.

**Comment by rhattersley** [comment]
Where are they? I couldn't find a link from the [code](https://github.com/pyugrid/pyugrid) or the [docs](http://pyugrid.github.io/pyugrid).

**Comment by rhattersley** [comment]
> Where are they?

[Doh!](https://github.com/pyugrid/pyugrid/tree/master/notebook_examples) :unamused:
