### ISSUE TITLE
Bad merge

### ISSUE THREAD

**Issue by ocefpaf** [pyugrid/pyugrid#114]
Apparently we had a bad merge at some point and `ugrid_wx.py` is corrupted.

https://github.com/pyugrid/pyugrid/commit/44e3cfda3c93bc614bc44e8e2eecfda13815164e#commitcomment-16058922

I could not find a PR that correspond to that change, nor we have tests that could catch it.

I am working in the tests now\* but we need to figure out what to do with that file:

- revert to a previous state?
- ask the original author to fix it?
- remove `ugrid_wx.py` from pyugrid and let that be a separate module?

\* Simple `flake8` run that will catch things like this.

**Comment by ChrisBarker-NOAA** [comment]
what's the status of this? All my fault, i was messing around with reading non-ugrid files, and did not mean to commit the changes to ugrid_wx.py

Do I need to go in and clean that up?

**Comment by ocefpaf** [comment]
> Do I need to go in and clean that up?

What do you think about those 3 suggestions?  I am leaning towards the last one.

I like the wx stuff, but should that be part of the `pyugrid` module?  wxPython is problematic as a dependency and the code GUI won't be used in applications that need a lightweight implementation of `pyugrid` (like `sci-wms`, `xrray`, `iris`, etc).

Pinging @cbcunc, @rsignell-usgs and @rhattersley for their option too.

**Comment by ChrisBarker-NOAA** [comment]
I'd like to leave it in -- it's really too small to bother with a package all its own, and small enough not to get in the way.

It's fine to not have it as a listed dependency -- conda nor pip have a good way to handle optional dependencies, but I could add some code to have it give a nice message if wx isn't there at run time.

So it can just sit there and not get in the way.

(and I'll try not to break it again :-) )

**Comment by ocefpaf** [comment]
- revert to a previous state?
- ask the original author to fix it?
- ~~remove ugrid_wx.py from pyugrid and let that be a separate module?~~

I can do the first option, but I guess you are the author in case you want the latter, right?

**Comment by ChrisBarker-NOAA** [comment]
yeah, let me fix it -- there may be a change or two in there we want to keep.

**Comment by ChrisBarker-NOAA** [comment]
OK -- cleaned up and pushed to master.
