### ISSUE TITLE
print statements in test files 

### ISSUE THREAD

**Issue by ocefpaf** [pyugrid/pyugrid#115]
There are many `print()` statements on several test files.  I guess they were added for debugging, but I wonder if it is time to remove them.

@ChrisBarker-NOAA I can send a PR for that.  I just want to her from you first.  Maybe there is another reason for those print statements.

**Comment by ChrisBarker-NOAA** [comment]
well, the test frameworks capture stdout, and only show it when there is a failure -- when it's nice to have them.

It's kind of a style thing as to whether to leave them or not once the tests are all running fine. In theory, I remove them, but I guess I get lazy.

So: go ahead and remove them if you want, but I don't see it as important.

**Comment by ocefpaf** [comment]
> So: go ahead and remove them if you want, but I don't see it as important.

I agree that it is not important, but it is a distraction when reading the test code and adding new tests.  BTW pytest does a good job of output the failure information at various levels of verbosity.

**Comment by ChrisBarker-NOAA** [comment]
sounds good.

BTW, thanks for doing all this housekeeping!

**Comment by ocefpaf** [comment]
> BTW, thanks for doing all this housekeeping!

I am working on some of the APIRUS improvements we discussed.  I already started with `pysgrid` (see https://github.com/sgrid/pysgrid/pull/77 and https://github.com/sgrid/pysgrid/pull/72). However, `pyugrid` has a bigger code base and I need to familiarize myself with the it first.  Housekeeping stuff is good for that :wink:

The first PR will be the proposal to remove the `from_ncfile` and `from_nc_dataset` and add a single `load_grid` method.

**Comment by ChrisBarker-NOAA** [comment]
The first PR will be the proposal to remove the from_ncfile and
from_nc_dataset and add a single load_grid method.

Yeah, can't remember why I did it that way. It is kind of klunky.





—
Reply to this email directly or view it on GitHub
<https://github.com/pyugrid/pyugrid/issues/115#issuecomment-183426908>.

**Comment by ocefpaf** [comment]
I'll start as soon as we solve #116 to avoid merge conflicts.

Not sure about the state of #98  and #111.  It would be nice to get those two sorted out as well.
