### ISSUE TITLE
Write unittest for `io.utils.py`

### ISSUE THREAD

**Issue by ocefpaf** [pyugrid/pyugrid#121]
The file:

https://github.com/pyugrid/pyugrid/blob/02786a40786c9dde3305e181aa534f7aef83354d/test/test_io_util.py

introduced in https://github.com/pyugrid/pyugrid/commit/02786a40786c9dde3305e181aa534f7aef83354d has no tests.  I can assign myself if no one else is working on this.

Ping @ChrisBarker-NOAA to create the assignment as I do not have adim right here.

PS: Naming a submodule `io` is usually a headache and I would recommend against it.

See http://stackoverflow.com/questions/12011327/using-absolute-import-and-handling-relative-module-name-confilcts-in-python

**Comment by ChrisBarker-NOAA** [comment]
This really needs more than unit tests -- it needs to be fleshed out, which I haven't had the chance to do.

But this is code for helping you write a ugrid reader for non UGRID-compliant files -- so we need a non-UGRID complient test file to test against. I had one I needed to import, but we need a way to handle larger binary test files before we can really do this.

I think this one could be used:

https://gnome.orr.noaa.gov/py_gnome_testdata/COOPSu_CREOFS.nc

But it's 18MB of binary we don't want to put in the repo!

A smaller one would be nice, too...

And yes, probably renaming the io sub-package would be good -- the idea is this is were IO code would go though, like other file formats, etc... shapefiles, kml, ....

**Comment by ocefpaf** [comment]
> But it's 18MB of binary we don't want to put in the repo!

Agreed. But I downloaded it here anyway to start playing with this.

> And yes, probably renaming the io sub-package would be good -- the idea is this is were IO code would go though, like other file formats, etc... shapefiles, kml, ....

How about `grid_io`?

**Comment by ChrisBarker-NOAA** [comment]
How about grid_io?

Sure. Go for it :-)

-CHB

**Comment by ChrisBarker-NOAA** [comment]
looks like #132 deals with this -- closing.
