### ISSUE TITLE
load_grid method/function

### ISSUE THREAD

**Issue by ocefpaf** [pyugrid/pyugrid#125]
I implemented a `load_grid` static method on `pysgrid` and, as we discussed in APIRUS, I am working on implementing the same here.

Right now we have 4 ways of loading the grid.  The UGrid class methods `UGrid.from_ncfile` and `UGrid.from_nc_dataset` and the functions `load_grid_from_ncfilename` and `load_grid_from_ncfilename` and `load_grid_from_nc_dataset`.

My plan is to implement the function `load_grid_from_nc_dataset` as a class method named `load_grid` and make it take either a string or a `netCDF4.Dataset`.  This function already takes the `UGrid` class as its input, so it is natural to become a method of that class.  Then I will write a thin wrapper for that method named `load_grid` so people from do:

```python
from pyugrid import load_grid

ug = load_grid(nc_url)
```

Akin to `pysgrid`'s API.

Any thoughts?

**Comment by ChrisBarker-NOAA** [comment]
This all looks good -- I _think_ we had a reason for the separate methods at some point, but I can't remember what it was. So good to clean this up.

**Comment by ocefpaf** [comment]
This works fine in `pysgrid`, but the internal logic there is slightly different than here. The main difference is that, in `pysgrid`m we pass netCDF variables instead of executing the full slices to get the deferred load for free and get the ugrid object right away without downloading the data immediately. Another one is the `nodes_{lon,lat}` attributes instead of the 2D `nodes` array.

> I *think* we had a reason

This is far from ready.  We need to add remote URL tests BTW.  In my local machine this is hanging on all OPeNDAP URLs I tried! Not sure why yet :unamused: 

Also, there is a lot of code in `load_grid` that could be factored out as a `compliance-checker` step. I need to ready the UGRID-0.9 first though.

**Comment by ChrisBarker-NOAA** [comment]
This is in a PR now, yes? -- so closing.
