### ISSUE TITLE
dev version?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [pyugrid/pyugrid#134]
@ocefpaf  recently cleaned up the version handling -- we now simple set it in the **init**.py

but our most recent tag is 1.1.6, and the version string in master is 1.1.7, which is good. But maybe it should be "1.1.7dev"  or something, so that it's clear if anyone pulls from master that they are not getting a release.

**Comment by ocefpaf** [comment]
The current released version is `v0.1.6`. PR #128 set is to `v0.2.0` (I will add the deve):

https://github.com/ocefpaf/pyugrid/commit/dab576916675ec8547c222d23c3c4c947482e91a#diff-9705109aa146a786dee6f2b80f1b01afR13

PS: Let's stop bumping the micro number, that usually represent bug fixes, and start bumping the major and macro.

**Comment by ChrisBarker-NOAA** [comment]
great, thanks!

well, we should follow semantic versioning rules -- bump the minor if you change the API -- which we have recently done with load_grid -- so yes, that's the way to go now.

I suppose also major enhancements should bump the minor, too.

IIRC, we bumped the micro number a lot when we were struggling with the pypi upload :-)

We should have some idea when we're going to go to 1.0 though ....
