### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ocefpaf** [pyugrid/pyugrid#140]
What type of BSD is used here? 2 or 3 Clauses? It would be nice to have a `LICENSE.txt` file too.

**Comment by ChrisBarker-NOAA** [comment]
either one is fine with me.

As a US Federal Employee, everything I write is Public Domain anyway...

and yes, once we decide, we certainly need a LICENCE.txt file

**Comment by ocefpaf** [comment]
Ping!

**Comment by ChrisBarker-NOAA** [comment]
It looks like numpy uses the three clause license:

http://www.numpy.org/license.html

so following in their lead makes sense to me.

However, I am a bit confused about copyright in this case -- inteh numpycase, it says:

Copyright © 2005-2016, NumPy Developers.
All rights reserved.

So I suppose we can put "pyugrid developers" 

But that isn't an actual legal entity -- can it hold a copyright????

**Comment by ChrisBarker-NOAA** [comment]
lookng into this more, I see, in teh MPL docs:

"""
matplotlib uses a shared copyright model. Each contributor maintains copyright over their contributions to matplotlib. But, it is important to note that these contributions are typically only changes to the repositories. Thus, the matplotlib source code, in its entirety, is not the copyright of any single person or institution. Instead, it is the collective copyright of the entire matplotlib Development Team. If individual contributors want to maintain a record of what changes/contributions they have specific copyright on, they should indicate their copyright in the commit message of the change, when they commit the change to one of the matplotlib repositories.

The Matplotlib Development Team is the set of all contributors to the matplotlib project. A full list can be obtained from the git version control logs.
"""

It seems we should put text similar to this in here.

**Comment by ocefpaf** [comment]
:+1:  on the `BSD 3-Clause`. No idea on the copyright stuff though.

**Comment by ChrisBarker-NOAA** [comment]
OK -- PR done:  #149
