### ISSUE TITLE
Submit a sprint for SciPy 2016

### ISSUE THREAD

**Issue by dharhas** [pyugrid/pyugrid#141]
Hey Y'all,

Are any of you attending SciPy 2016 & the Sprints? The last couple of years y'all sprinted on pyugrid. If you are planning to again, I'd like to request that you fill out the sprint registration form so folks now about it - http://scipy2016.scipy.org/ehome/146062/332969/?&&

- dharhas

**Comment by ChrisBarker-NOAA** [comment]
I'll be there, and sure py_ugrid is as good anything to sprint on (or APIRUS and/or pysgrid)

**Comment by ChrisBarker-NOAA** [comment]
all over now....
