### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by QuLogic** [pyugrid/pyugrid#147]
The latest tagged release is 0.2.2. The small description on the front page here links to http://pyugrid.github.io/pyugrid, which claims to be documentation for 0.1.3. (Also, it should be an https link.)

**Comment by rsignell-usgs** [comment]
@jay-hennen , since you issued the last release https://github.com/pyugrid/pyugrid/releases, can you handle this issue please?

**Comment by ChrisBarker-NOAA** [comment]
On Tue, Oct 11, 2016 at 6:29 AM, Rich Signell <notifications@github.com>
wrote:

> @jay-hennen <https://github.com/jay-hennen> , since you issued the last
> release https://github.com/pyugrid/pyugrid/releases, can you handle this
> issue please?
>
I'll do it.

But for the future, it wuld be better if a CI could do this for us --
anyone know how to trigger a CI run when a release is tagged?

Also --those docs are really minimal anyway -- good for them to be up to
date, but better for them to be good :-)

So -- PRs for better docs welcome!

-CHB

**Comment by ChrisBarker-NOAA** [comment]
Docs updated on gh-pages, and cleaned up documentation in PR: #148

**Comment by QuLogic** [comment]
Please correct the link as well. Also, PyPI is also outdated, looks like...

**Comment by ChrisBarker-NOAA** [comment]
yeah -- no one ever did a PyPI release...

I'll see what I can do about that.

**Comment by ChrisBarker-NOAA** [comment]
@QuLogic: what's wrong with the link? it points to the latest published version of the docs, as it should.

**Comment by ChrisBarker-NOAA** [comment]
OK -- 0.2.2 pushed to PyPI

The PyPI search is broken, so who knows if anyone will find it, but it's there :-)

**Comment by QuLogic** [comment]
I mean this link should be https:
![untitled](https://cloud.githubusercontent.com/assets/302469/19455700/0a564984-948c-11e6-817a-ee35efd457ed.png)

**Comment by ChrisBarker-NOAA** [comment]
but it IS http: -- github.io seem happy with either.

Any reason public docs should be served out via https?

But I changed it -- easy enough, and why not?

**Comment by QuLogic** [comment]
Yes, it supports both; at this point, there's no reason _not_ to use https.
