### ISSUE TITLE
Code sprint at Scipy 2014?

### ISSUE THREAD

**Issue by rsignell-usgs** [pyugrid/pyugrid#18]
Pyugrid gang, anyone interested in a code sprint at SciPy 2014 (just over two weeks away?)  I'm going to be staying through Friday, flying home 11am on Saturday.

**Comment by ocefpaf** [comment]
Another issue that can be closed.

**Comment by ChrisBarker-NOAA** [comment]
we can start a new one for this year if it's relevant.

**Comment by ocefpaf** [comment]
> We can start a new one for this year if it's relevant.

:+1:
