### ISSUE TITLE
Time to follow the Fork=>Branch=>PR=>Review=>Merge process?

### ISSUE THREAD

**Issue by rsignell-usgs** [pyugrid/pyugrid#20]
I know that on a young project, it seems like a pain to use the `Fork=>Branch=>PR=>Review=>Merge` process, but maybe it's time?  

I like these resources:
https://gun.io/blog/how-to-github-fork-branch-and-pull-request/
http://nathanhoad.net/git-workflow-forks-remotes-and-pull-requests

Each PR should be closing one or more issues.
What do others think?

**Comment by ocefpaf** [comment]
I guess most of us is using that work-flow.  We should close this issue and write some coding standards/developer guide in the wiki or in the docs.

I really like iris' docs for that:

http://scitools.org.uk/iris/docs/latest/developers_guide/index.html

(BTW I believe we can close this issue too.)

**Comment by ChrisBarker-NOAA** [comment]
Good idea to have a guide -- maybe this isn't big enough to need something as extensive as Iris' -- but why not? I say we start by cribbing theirs.

**Comment by rsignell-usgs** [comment]
@ChrisBarker-NOAA , awesome.   Sounds like we are all on board.
