### ISSUE TITLE
Can no longer open testbed UGRID files 

### ISSUE THREAD

**Issue by rsignell-usgs** [pyugrid/pyugrid#23]
I can't open the IOOS testbed UGRID files with pyugrid anymore.
http://nbviewer.ipython.org/gist/rsignell-usgs/bbbd6b38825f3d8c9439

I see at least one problem here:
https://github.com/pyugrid/pyugrid/blob/84aa40a6ebcdfff9c015aac53eb66e3538e0509b/pyugrid/read_netcdf.py#L55
in that `role` should be `cf_role`.

**Comment by ocefpaf** [comment]
@rsignell-usgs a new version of that notebook works:

http://nbviewer.jupyter.org/gist/ocefpaf/622faf8cdeaa666edcee

@ChrisBarker-NOAA let's close this issue.

**Comment by ocefpaf** [comment]
@rsignell-usgs GitHub failed to close this automatically. This was solved by #117.

**Comment by rsignell-usgs** [comment]
Yes, closing here.
