### ISSUE TITLE
Consider replacing None with 0

### ISSUE THREAD

**Issue by rsignell-usgs** [pyugrid/pyugrid#31]
Could we use a 0-sized array instead of `None`, for example if there are no edges or face?
The advantage of 0-sized array is that then we could do things like:
```
print "There are %i nodes"%ug.nodes.shape[0]
print "There are %i edges"%ug.edges.shape[0]
print "There are %i faces"%ug.faces.shape[0]
```

**Comment by ocefpaf** [comment]
With `None` one can write this:

```python
if not ug.edges:
    ug.build_edges()
```

Verbose but very readable. Note that getting a `tuple` or `None` is OK with many APIs out there.

Are you OK closing this @rsignell-usgs?

**Comment by ChrisBarker-NOAA** [comment]
well, it should be:
```
if ug.edges is not None:
    ug.build_edges()
```
but anyway, I think non edges is different than zero edges -- you should only get zero edges if the mesh has zero faces....

I'll close, and someone can re-open if s/he really thinks this is the wrong way to go.
