### ISSUE TITLE
Sci-WMS Discussing Pyugrid Integration

### ISSUE THREAD

**Issue by cbcunc** [pyugrid/pyugrid#40]
Sci-WMS developer are [discussing](https://github.com/asascience-open/sci-wms/issues/120) integrating pyugrid for the purposes of compliance checking. More realistically, pyugrid may be able to reduce complexity in some ugrid handling in sci-wms. This issue is for awareness and to promote cross-project collaboration. We should know what the sci-wms requirements for pyugrid are and if they can be satisfied in desired time frames.

**Comment by ocefpaf** [comment]
Latest sci-wms uses `pyugrid` and of the points here are outdated.  I recommend we close this issue and ask @kwilcox to open new (and more specific) ones.

**Comment by kwilcox** [comment]
:+1:
