### ISSUE TITLE
If only we had a tool that would draw the mesh...

### ISSUE THREAD

**Issue by cbcunc** [pyugrid/pyugrid#50]
...if only.

**Comment by ocefpaf** [comment]
There is also
-  [OCGIS tools](https://github.com/NCPP/ocgis):  I  believe it can read ugrid;
- [gridgeo](https://github.com/pyoceans/gridgeo): use `pyugrid` to save shapefiles, GeoJSONs, etc;
- another one that @cbcunc mention at SciPy 2015 but I cannot remember;
- the example notebooks in the repository.

So I guess we have plenty options.  Close this one?
