### ISSUE TITLE
py_ugrid virtual sprint?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [pyugrid/pyugrid#53]
Hi folks,

This issues have been stacking up, but no much code written. Perhaps we need some motivation to buckle down and get some stuff done.

How about a virtual sprint? A handful of us would set aside a day or two work on py_ugrid. If we  all set aside the same days, then we could coordinate some, and I think really get some work done.

Of course with time zones, we wouldn't be working at exactly the same time, but we should be able to have some overlap.

honestly, I have no idea when I could find the time for this, but I should be abel to put aside a day or two at some point.

**Comment by ocefpaf** [comment]
I believe that this issue can be closed.

**Comment by ChrisBarker-NOAA** [comment]
Still a good idea... but @ocefpaf has been doing a one-man sprint!

**Comment by ocefpaf** [comment]
> but @ocefpaf has been doing a one-man sprint!

I it is never a `one-man` when using GitHub and PR &rarr; Review  &rarr; Merge workflow :wink: 

(I always blame all bad code I write on the reviewer. :smiling_imp:)
