### ISSUE TITLE
SciPy 2015 Sprint?

### ISSUE THREAD

**Issue by cbcunc** [pyugrid/pyugrid#58]
I would like to register a pyugrid sprint at SciPy 2015:

http://www.scipy2015.scipy.org/ehome/115969/259290/?&

However, I'd like some consensus that's a good thing before doing so. We could work on cleaning up some of these lingering issues and get a better roadmap going.

How many of you usual suspects will be at SciPy 2015 and would you like to sprint on pyugrid again?

**Comment by ChrisBarker-NOAA** [comment]
I'll be there, and would love to push py_ugrid forward some more.

-Chris


On Thu, Jun 4, 2015 at 8:31 AM, Chris Calloway <notifications@github.com>
wrote:

> I would like to register a pyugrid sprint at SciPy 2015:
>
> http://www.scipy2015.scipy.org/ehome/115969/259290/?&
>
> However, I'd like some consensus that's a good thing before doing so. We
> could work on cleaning up some of these lingering issues and get a better
> roadmap going.
>
> How many of you usual suspects will be at SciPy 2015 and would you like to
> sprint on pyugrid again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyugrid/pyugrid/issues/58>.
>



-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by rhattersley** [comment]
Nice idea. :+1: Sadly I won't make it over this year. :disappointed:

**Comment by cbcunc** [comment]
OK, I registered the sprint. But I'm going to leave this issue open for awhile to give people a chance to sound off about their participation. @rhattersley, I'm sorry we are going to miss you thing time. Maybe I can swing by Exeter again before next year. But @pelson is going to be at SciPy15, correct?

**Comment by rhattersley** [comment]
Yes - @pelson will be there. I almost cc'd him in my previous reply, but I'm guessing he'll be up to his ears in matplotlib and/or cartopy. I can't hurt to ask though...

**Comment by rsignell-usgs** [comment]
I have to leave in time to get back to the cape by 6 pm on Saturday,but I'm interested

**Comment by ocefpaf** [comment]
I guess this one can be close :wink: 

(Or updated to 2016!)

**Comment by ChrisBarker-NOAA** [comment]
YUp -- I jsut got the note about SciPy this year, and will likely be there -- hopefully many of us will.

But let's wait before planning stuff.
