### ISSUE TITLE
Add an example notebook that plots velocity vectors using pyugrid

### ISSUE THREAD

**Issue by rsignell-usgs** [pyugrid/pyugrid#60]
Does anyone have an example notebook that shows how to use pyugrid to plot velocity vectors from any UGRID-compliant model (e.g. without model specific code)?

**Comment by ocefpaf** [comment]
@rsignell-usgs GitHub failed to close this automatically. This was solved by #117.

**Comment by rsignell-usgs** [comment]
Strange that Github didn't close this. But yes, we have a example now
at 
https://github.com/pyugrid/pyugrid/blob/master/notebook_examples/vector_plotting_example.ipynb
(thanks @ocefpaf)
p.s.  do streamlines work correctly with unstructured grid data?

**Comment by ocefpaf** [comment]
> p.s. do streamlines work correctly with unstructured grid data?

Not sure.  I guess that the issue there might be the masked array, but that needs more digging.

**Comment by rsignell-usgs** [comment]
I'm reopening this here because this isn't really an interoperable UGRID velocity example.   I tried a FVCOM dataset (url = ('http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts/NECOFS_GOM3_FORECAST.nc')
and it did not produce the correct plot.    The example 
https://github.com/pyugrid/pyugrid/blob/master/notebook_examples/vector_plotting_example.ipynb
assumes that the velocity points are at the nodes, which is not the case for FVCOM. 

The logic should be to read the `mesh` attribute for the variable of interest (in this case barotropic velocity) along with the `location` attribute, and then read the lon,lat coordinates from the appropriate variables identified in the `mesh` variable.   

For this FVCOM dataset we would read the elevation variable and find:

```
mesh: fvcom_mesh
location: face
```
that would lead to selecting `lonc`, `latc` from:
```
node_coordinates: lon lat
face_coordinates: lonc latc
```

Make sense? 
This should be a pyugrid function if not already there, no?

**Comment by ocefpaf** [comment]
> The example assumes that the velocity points are at the nodes, which is not the case for FVCOM.

Makes sense.  Let's just change the issue title to be `interoperable UGRID velocity example` and I will re-visit it soon. (Want to finish the `load_grid` stuff first.)
