### ISSUE TITLE
Active development plan?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [pyugrid/pyugrid#86]
Post scipy, we have:

tagged a release -- freeing us up to go mess things up.

WE've also planned a bunch of re-factoring that WILL break most code thatused pyugrid.

So what's the plan? I suggest we just go for it and push the changes to master. 

Alternatively, we could create a branch to do all the refactoring in, and then get it all settled before merging with master.

However, we do need a working branch that we push changes to early and often, so we don't get all out of sync with each-other.

**Comment by ocefpaf** [comment]
> I suggest we just go for it and push the changes to master.

I think that sending small PRs and merging them to master is probably better than working on a branch.  A branch can get stale quickly and new contributor will look for changes in master.

**Comment by ocefpaf** [comment]
@ChrisBarker-NOAA and @rsignell-usgs in a way this is a duplicate of #20.

**Comment by ChrisBarker-NOAA** [comment]
yup, this is kind of stale now -- closing.
