### ISSUE TITLE
Consider using  Versioneer for version handling

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [pyugrid/pyugrid#90]
As suggested by Phil in #71

**Comment by ocefpaf** [comment]
#71 turn out to be a bad pattern and `versioneer`, even though it is very cool, needs [a lot of bolierplate](https://github.com/SciTools/biggus/pull/109/files) that I don't think we need in a small project like `pyugrid`.

I reverted #71 to a pattern that is commonly used in many projects, including Phil's cartopy and iris :wink:, in https://github.com/pyugrid/pyugrid/commit/536af1d0e97de64c958e2b87ba1ea00038331979.
