### ISSUE TITLE
Look into PySeidon

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [pyugrid/pyugrid#99]
I just discovered this:

https://github.com/GrumpyNounours/PySeidon

Kind of special purpose,a nd designed for a particular use case -- but has a lot of generally useful stuff, and works with FVCOM, which is a subset of the general UGRID case. Nice to share some code there.

Of course, PySeidon should really be built on py_ugrid, but that can wait :-)

But we should see what's there.

**Comment by rsignell-usgs** [comment]
Here's how the vertical slice is done.  :smile_cat: https://github.com/GrumpyNounours/PySeidon/blob/master/pyseidon/fvcomClass/functionsFvcomThreeD.py#L217-L269

**Comment by ocefpaf** [comment]
Close this issue? @rsignell-usgs and I looked a lot at that code :smile_cat:

**Comment by ChrisBarker-NOAA** [comment]
Let's just remember to look at that code as we move forward.
